import { Prefecture } from "@prisma/client";

export const prefectureValues = [
  Prefecture.HOKKAIDO,
  Prefecture.AOMORI,
  Prefecture.IWATE,
  Prefecture.MIYAGI,
  Prefecture.AKITA,
  Prefecture.YAMAGATA,
  Prefecture.FUKUSHIMA,
  Prefecture.IBARAKI,
  Prefecture.TOCHIGI,
  Prefecture.GUNMA,
  Prefecture.SAITAMA,
  Prefecture.CHIBA,
  Prefecture.TOKYO,
  Prefecture.KANAGAWA,
  Prefecture.NIIGATA,
  Prefecture.TOYAMA,
  Prefecture.ISHIKAWA,
  Prefecture.FUKUI,
  Prefecture.YAMANASHI,
  Prefecture.NAGANO,
  Prefecture.GIFU,
  Prefecture.SHIZUOKA,
  Prefecture.AICHI,
  Prefecture.MIE,
  Prefecture.SHIGA,
  Prefecture.KYOTO,
  Prefecture.OSAKA,
  Prefecture.HYOGO,
  Prefecture.NARA,
  Prefecture.WAKAYAMA,
  Prefecture.TOTTORI,
  Prefecture.SHIMANE,
  Prefecture.OKAYAMA,
  Prefecture.HIROSHIMA,
  Prefecture.YAMAGUCHI,
  Prefecture.TOKUSHIMA,
  Prefecture.KAGAWA,
  Prefecture.EHIME,
  Prefecture.KOCHI,
  Prefecture.FUKUOKA,
  Prefecture.SAGA,
  Prefecture.NAGASAKI,
  Prefecture.KUMAMOTO,
  Prefecture.OITA,
  Prefecture.MIYAZAKI,
  Prefecture.KAGOSHIMA,
  Prefecture.OKINAWA,
] as const;

const prefectureLabels = {
  [Prefecture.HOKKAIDO]: "北海道",
  [Prefecture.AOMORI]: "青森県",
  [Prefecture.IWATE]: "岩手県",
  [Prefecture.MIYAGI]: "宮城県",
  [Prefecture.AKITA]: "秋田県",
  [Prefecture.YAMAGATA]: "山形県",
  [Prefecture.FUKUSHIMA]: "福島県",
  [Prefecture.IBARAKI]: "茨城県",
  [Prefecture.TOCHIGI]: "栃木県",
  [Prefecture.GUNMA]: "群馬県",
  [Prefecture.SAITAMA]: "埼玉県",
  [Prefecture.CHIBA]: "千葉県",
  [Prefecture.TOKYO]: "東京都",
  [Prefecture.KANAGAWA]: "神奈川県",
  [Prefecture.NIIGATA]: "新潟県",
  [Prefecture.TOYAMA]: "富山県",
  [Prefecture.ISHIKAWA]: "石川県",
  [Prefecture.FUKUI]: "福井県",
  [Prefecture.YAMANASHI]: "山梨県",
  [Prefecture.NAGANO]: "長野県",
  [Prefecture.GIFU]: "岐阜県",
  [Prefecture.SHIZUOKA]: "静岡県",
  [Prefecture.AICHI]: "愛知県",
  [Prefecture.MIE]: "三重県",
  [Prefecture.SHIGA]: "滋賀県",
  [Prefecture.KYOTO]: "京都府",
  [Prefecture.OSAKA]: "大阪府",
  [Prefecture.HYOGO]: "兵庫県",
  [Prefecture.NARA]: "奈良県",
  [Prefecture.WAKAYAMA]: "和歌山県",
  [Prefecture.TOTTORI]: "鳥取県",
  [Prefecture.SHIMANE]: "島根県",
  [Prefecture.OKAYAMA]: "岡山県",
  [Prefecture.HIROSHIMA]: "広島県",
  [Prefecture.YAMAGUCHI]: "山口県",
  [Prefecture.TOKUSHIMA]: "徳島県",
  [Prefecture.KAGAWA]: "香川県",
  [Prefecture.EHIME]: "愛媛県",
  [Prefecture.KOCHI]: "高知県",
  [Prefecture.FUKUOKA]: "福岡県",
  [Prefecture.SAGA]: "佐賀県",
  [Prefecture.NAGASAKI]: "長崎県",
  [Prefecture.KUMAMOTO]: "熊本県",
  [Prefecture.OITA]: "大分県",
  [Prefecture.MIYAZAKI]: "宮崎県",
  [Prefecture.KAGOSHIMA]: "鹿児島県",
  [Prefecture.OKINAWA]: "沖縄県",
} satisfies Record<Prefecture, string>;

export const prefectures = prefectureValues.map((value) => ({
  value,
  label: prefectureLabels[value],
}));
